version: '3'
services:
  javaapp:
    build:
      context: .
      dockerfile: Dockerfile
    image:  registry.gitlab.com/taskpro/app:latest     
    ports:
      - 5001:80
    volumes:
      - ./app:/app
    networks:
      - taskpro-javaapp
networks:
  taskpro-javaapp: