apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-app
  name: java-app
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "app-port"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: java-app
